// examples/react-redux/src/App.js
import React from "react";
import Subspace from "@embarklabs/subspace";
import web3 from './web3';
import MyContract from './MyContract';
import { connect } from "react-redux";
import { myAction } from './actions';
import PropTypes from 'prop-types';

let MyContractInstance;
let eventSubscription;

class App extends React.Component {
  async componentDidMount() {
    MyContractInstance = await MyContract.getInstance();

    const subspace = new Subspace(web3.currentProvider);
    await subspace.init();
    eventSubscription = subspace.trackEvent(MyContractInstance, "MyEvent", { filter: {}, fromBlock: 1 })
                                   .subscribe(this.props.myAction);
  }

  componentWillUnmount(){
    eventSubscription.unsubscribe();
  }

  createTrx = () => {
    MyContractInstance.methods
      .myFunction()
      .send({ from: web3.eth.defaultAccount });
  };

  render() {
    const { data } = this.props;
    
    return (
      <div>
        <button onClick={this.createTrx}>Create a Transaction</button>
        <ul>
          <li><b>someValue: </b> {data.someValue}</li>
          <li><b>anotherValue: </b> {data.anotherValue}</li>
        </ul>
      </div>
    );
  }
}

App.propTypes = {
  data: PropTypes.object,
  myAction: PropTypes.func
};

export default connect(
  ({ data }) => ({ data }),
  { myAction }
)(App);

// examples/vue/src/App.vue
<template>
  <div id="app">
    <button v-on:click="createTrx">Create a Transaction</button>
    <MyComponent v-bind:event-data="myEventObservable$" v-if="!!myEventObservable$" />
  </div>
</template>

<script>
import MyComponent from './components/MyComponent.vue'
import Subspace from "@embarklabs/subspace";
import web3 from './web3';
import MyContract from './MyContract';

export default {
  name: 'app',
  data: function(){
    return {
      myEventObservable$: null,
      MyContractInstance: null
    };
  },
  created: async function(){
    this.MyContractInstance = await MyContract.getInstance(); 

    const subspace = new Subspace(web3.currentProvider);
    await subspace.init();

    this.myEventObservable$ = subspace.trackEvent(this.MyContractInstance, "MyEvent", {filter: {}, fromBlock: 1 });
  }, 
  methods: {
    createTrx: function(){
      this.MyContractInstance.methods
        .myFunction()
        .send({ from: web3.eth.defaultAccount });
    }
  },
  components: {
    MyComponent
  }
}
</script>
