// examples/vue/src/App.vue
<template>
  <div id="app">
    <button v-on:click="createTrx">Create a Transaction</button>
    <MyComponent v-bind:event-data="myEventObservable$" v-if="!!myEventObservable$" />
  </div>
</template>

<script>
import MyComponent from './components/MyComponent.vue'
import Subspace from "@status-im/subspace";
import web3 from './web3';
import MyContract from './MyContract';

export default {
  name: 'app',
  data: function(){
    return {
      myEventObservable$: null,
      MyContractInstance: null
    };
  },
  created: async function(){
    this.MyContractInstance = await MyContract.getInstance(); 

    const subspace = new Subspace(web3.currentProvider);
    await subspace.init();

    this.myEventObservable$ = subspace.trackEvent(this.MyContractInstance, "MyEvent", {filter: {}, fromBlock: 1 });
  }, 
  methods: {
    createTrx: function(){
      this.MyContractInstance.methods
        .myFunction()
        .send({ from: web3.eth.defaultAccount });
    }
  },
  components: {
    MyComponent
  }
}
</script>

// examples/svelte/src/App.svelte
<script>
// import web3 from './web3';
// import MyContract from './MyContract';
import { onMount } from 'svelte';
import Subspace from "@status-im/subspace";

let MyContractInstance;
let subspace;
let myEventObservable$;

onMount(async () => {
  //MyContractInstance = await MyContract.getInstance(); 

 // subspace = new Subspace(web3.currentProvider);
  // await subspace.init();

  //myEventObservable$ = subspace.trackEvent(MyContractInstance, "MyEvent", {filter: {}, fromBlock: 1 });
});


let name = 'world';
	
</script>

<h1>Hello {name}!</h1>
